version: '3.9'
services:
  redis:
    image: redis/redis-stack:6.2.2-v4
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    name: custom_backend
