version: '3.9'
services:
  redis:
    image: redis/redis-stack:6.2.2-v4
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
    networks:
      - backend
  mongodb:
    image: mongo:5
    restart: always
    networks:
      - backend
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpass
  mongo-express:
    image: mongo-express:latest
    restart: always
    networks:
      - backend
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpass
      ME_CONFIG_MONGODB_URL: mongodb://root:secretpass@mongodb:27017/

volumes:
  redis-data:
  mongo-data:

networks:
  backend:
    name: custom_backend
