name: "Auth Service CI"

on:
  pull_request:
    branches:
      - main
    paths:
      - "app/auth-service/**"

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: "app/auth-service"
    strategy:
      matrix:
        node: [24, 26]
    name: Build ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn compile
