name: "Docker Build"
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Dockerfile"
      - "docker-compose.yml"
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
